apiVersion: apps/v1
kind: Deployment
metadata:
  name: docker-ssh
  labels:
    app: docker-ssh-app
spec:
  selector:
    matchLabels:
      app: docker-ssh-app
  template:
    metadata:
      labels:
        app: docker-ssh-app
    spec:
      containers:
      - name: docker-ssh
        image: 192.168.56.12:43210/docker-ssh:0.0.2
        ports:
        - containerPort: 32450

---
apiVersion: v1
kind: Service
metadata:
  name: docker-ssh
spec:
  type: NodePort
  selector:
    app: docker-ssh-app
  ports:
    - name: client
      protocol: TCP
      port: 32450
      nodePort: 32450