apiVersion: apps/v1
kind: Deployment
metadata:
  name: docker-ssh-deployment
  namespace: docker-ssh-namespace
  labels:
    app: docker-ssh
spec:
  replicas: 1
  selector:
    matchLabels:
      app: docker-ssh
  template:
    metadata:
      labels:
        app: docker-ssh
    spec:
      volumes:
      - name: auth-key-vol
        secret:
          secretName: docker-ssh-credentials
      containers:
        - name: docker-ssh-container
          image: serhiiartiukh5465/docker_ssh
          env:
            - name: USER_NAME
              value: "ubuntu"
          command: ['/bin/sh', '-c', 'cp --verbose /tmp/secret /home/${USER_NAME}/.ssh/authorized_keys; 
                    chown ${USER_NAME}:${USER_NAME} /home/${USER_NAME}/.ssh/authorized_keys; 
                    chmod 600 /home/${USER_NAME}/.ssh/authorized_keys; 
                    /usr/sbin/sshd -D']
          ports:
          - containerPort: 32450
          volumeMounts:
          - name: auth-key-vol
            mountPath: /tmp/secret
            subPath: pubkey
          resources:
            limits:
              memory: 512Mi
              cpu: "0.6"
            requests:
              memory: 256Mi
              cpu: "0.3"
---
apiVersion: v1
kind: Service
metadata:
  name: docker-ssh-deployment
  namespace: docker-ssh-namespace
spec:
  type: NodePort
  selector:
    app: docker-ssh
  ports:
  - name: client
    protocol: TCP
    port: 32450
    nodePort: 32450