version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - USER_NAME=$USER_NAME
        - SSH_PORT=$SSH_PORT
        - USER_PASS=$USER_PASS
        - USER_ID=$USER_ID
    container_name: docker-ssh
    image: docker-ssh:0.0.2
    ports:
      - $SSH_PORT:$SSH_PORT/tcp
    # volumes:
    #   - type: bind
    #     source: ~/.ssh/docker_ssh_test/id_rsa.pub
    #     target: /home/$USER_NAME/.ssh/authorized_keys
    #     read_only: true