services:
  ssh_service:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - USER_NAME=$USER_NAME
        - SSH_PORT=$SSH_PORT
        - USER_PASS=$USER_PASS
        - USER_ID=$USER_ID
    container_name: docker_ssh
    image: docker_ssh:0.2
    ports:
      - $SSH_PORT:$SSH_PORT/tcp
    volumes:
      - type: bind
        source: ~/.ssh/hosts/docker_ssh_container/id_rsa.pub
        target: /home/${USER_NAME}/.ssh/authorized_keys
        read_only: true